<a href="https://colab.research.google.com/github/deepakdmane/ml/blob/main/Mutiple_linear_regression_data_processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# import Libraries

In [113]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [114]:
import csv
import random

# Define the number of records to generate
num_records = 100  # You can change this to the desired number

# Define lists of states and a range for numerical values
states = ["California", "Texas", "New York", "Florida", "Illinois"]
profit_range = (10000, 100000)  # Example range, adjust as needed
rnd_range = (5000, 50000)
admin_range = (10000, 30000)
marketing_range = (5000, 30000)

# Create the data
data = [["R&D Spend", "Administration", "Marketing Spend", "State","Profit"]]
for _ in range(num_records):
    profit = random.randint(*profit_range)
    rnd = random.randint(*rnd_range)
    admin = random.randint(*admin_range)
    marketing = random.randint(*marketing_range)
    state = random.choice(states)
    data.append([rnd, admin, marketing, state,profit])

# Save the data to a CSV file
file_path = "company_data1.csv"
with open(file_path, "w", newline="") as file:
    writer = csv.writer(file)
    writer.writerows(data)

print(f"CSV file '{file_path}' created successfully.")

CSV file 'company_data1.csv' created successfully.


# Import DataSET

In [116]:
try:
    dataset = pd.read_csv('company_data1.csv')
    display(dataset.head())
except FileNotFoundError:
    print("Error: 'Data.csv' not found. Please ensure the file exists in the current directory.")
except pd.errors.EmptyDataError:
    print("Error: 'Data.csv' is empty.")
except pd.errors.ParserError:
    print("Error: 'Data.csv' could not be parsed. Please check the file format.")
except Exception as e:
    print(f"An unexpected error occurred: {e}")

x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

,R&D Spend,Administration,Marketing Spend,State,Profit
0,36579,22505,5813,New York,98965
1,39708,21705,10476,Illinois,72784
2,48241,16652,25366,California,74474
3,27170,25495,12027,Florida,98185
4,27447,29342,9670,Florida,22180


In [117]:
print(x)

[[36579 22505 5813 'New York']
 [39708 21705 10476 'Illinois']
 [48241 16652 25366 'California']
 [27170 25495 12027 'Florida']
 [27447 29342 9670 'Florida']
 [46596 29470 24633 'California']
 [23790 23500 22617 'New York']
 [24115 15126 6620 'Florida']
 [13115 28106 29930 'Florida']
 [7185 18895 15075 'California']
 [10591 23590 29690 'Florida']
 [16517 24166 29833 'Illinois']
 [21268 27283 5734 'New York']
 [34268 23283 29097 'California']
 [14021 27052 7304 'Illinois']
 [18726 15984 11161 'Florida']
 [5583 11617 12653 'Texas']
 [5521 29920 28808 'California']
 [34389 16396 12694 'Texas']
 [40702 29484 20787 'Illinois']
 [33659 16171 17730 'Illinois']
 [16774 26644 8007 'New York']
 [13053 17386 21201 'New York']
 [14803 11106 29527 'Texas']
 [35948 11921 27531 'Florida']
 [9529 15220 13780 'New York']
 [22096 16329 24594 'Texas']
 [28994 23237 8165 'Florida']
 [40410 11993 29331 'New York']
 [24889 23217 16138 'Illinois']
 [14496 18390 17014 'Florida']
 [28409 28384 29086 'New York'

In [118]:
print(y)

[98965 72784 74474 98185 22180 39239 78813 22483 34978 41801 46761 43369
 97445 10650 43050 41039 47364 30014 98491 65527 41038 78121 35895 39891
 76244 62126 97345 97585 99960 75073 53102 34348 13101 74498 25857 66116
 98183 69897 47687 54946 23393 98917 63431 26432 21970 53037 37995 24597
 76075 75266 58988 29234 48725 69738 95478 39807 63956 27847 29466 31151
 10990 70219 61441 49437 82479 44137 68153 26315 40774 48336 22160 52431
 18175 17277 63814 45170 24661 25174 32267 33239 15830 24334 23080 32537
 25890 87756 23768 90724 87189 43881 70467 71050 99559 84533 17560 44312
 18936 13297 57264 23236]


# Encode Categorical Data

In [120]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
X = np.array(ct.fit_transform(x))

In [121]:
print(X)

[[0.0 0.0 0.0 1.0 0.0 36579 22505 5813]
 [0.0 0.0 1.0 0.0 0.0 39708 21705 10476]
 [1.0 0.0 0.0 0.0 0.0 48241 16652 25366]
 [0.0 1.0 0.0 0.0 0.0 27170 25495 12027]
 [0.0 1.0 0.0 0.0 0.0 27447 29342 9670]
 [1.0 0.0 0.0 0.0 0.0 46596 29470 24633]
 [0.0 0.0 0.0 1.0 0.0 23790 23500 22617]
 [0.0 1.0 0.0 0.0 0.0 24115 15126 6620]
 [0.0 1.0 0.0 0.0 0.0 13115 28106 29930]
 [1.0 0.0 0.0 0.0 0.0 7185 18895 15075]
 [0.0 1.0 0.0 0.0 0.0 10591 23590 29690]
 [0.0 0.0 1.0 0.0 0.0 16517 24166 29833]
 [0.0 0.0 0.0 1.0 0.0 21268 27283 5734]
 [1.0 0.0 0.0 0.0 0.0 34268 23283 29097]
 [0.0 0.0 1.0 0.0 0.0 14021 27052 7304]
 [0.0 1.0 0.0 0.0 0.0 18726 15984 11161]
 [0.0 0.0 0.0 0.0 1.0 5583 11617 12653]
 [1.0 0.0 0.0 0.0 0.0 5521 29920 28808]
 [0.0 0.0 0.0 0.0 1.0 34389 16396 12694]
 [0.0 0.0 1.0 0.0 0.0 40702 29484 20787]
 [0.0 0.0 1.0 0.0 0.0 33659 16171 17730]
 [0.0 0.0 0.0 1.0 0.0 16774 26644 8007]
 [0.0 0.0 0.0 1.0 0.0 13053 17386 21201]
 [0.0 0.0 0.0 0.0 1.0 14803 11106 29527]
 [0.0 1.0 0.0 0.0 0.0 359

# Splitting data into training data and test data

In [125]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.01, random_state = 0)

In [126]:
X_train, X_test, y_train, y_test

(array([[0.0, 0.0, 1.0, 0.0, 0.0, 38790, 18236, 7841],
        [1.0, 0.0, 0.0, 0.0, 0.0, 48241, 16652, 25366],
        [0.0, 1.0, 0.0, 0.0, 0.0, 25428, 29967, 25353],
        [0.0, 0.0, 0.0, 1.0, 0.0, 26941, 22581, 17865],
        [1.0, 0.0, 0.0, 0.0, 0.0, 31784, 29106, 14952],
        [0.0, 0.0, 0.0, 0.0, 1.0, 5583, 11617, 12653],
        [1.0, 0.0, 0.0, 0.0, 0.0, 15493, 25765, 28878],
        [1.0, 0.0, 0.0, 0.0, 0.0, 47334, 14820, 12726],
        [0.0, 0.0, 0.0, 1.0, 0.0, 37996, 10612, 19084],
        [1.0, 0.0, 0.0, 0.0, 0.0, 33288, 27767, 26010],
        [0.0, 1.0, 0.0, 0.0, 0.0, 35295, 17163, 16369],
        [0.0, 1.0, 0.0, 0.0, 0.0, 47354, 16244, 17866],
        [1.0, 0.0, 0.0, 0.0, 0.0, 34268, 23283, 29097],
        [0.0, 1.0, 0.0, 0.0, 0.0, 24115, 15126, 6620],
        [0.0, 1.0, 0.0, 0.0, 0.0, 14496, 18390, 17014],
        [0.0, 0.0, 0.0, 1.0, 0.0, 13053, 17386, 21201],
        [0.0, 1.0, 0.0, 0.0, 0.0, 35948, 11921, 27531],
        [0.0, 0.0, 0.0, 0.0, 1.0, 21034, 22161, 298

#Training the multiple linear Regression model on the training set

In [127]:
from sklearn.linear_model import LinearRegression
regression = LinearRegression()
regression.fit(X_train, y_train)

LinearRegression()

#Predicting the test set results

In [128]:
ypred = regression.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((ypred.reshape(len(ypred),1), y_test.reshape(len(y_test),1)),1))

[[47586.05 97345.  ]]
